Release/v5.1.1
bcgsc/pori_graphkb_loader pull request #17
Opened 2021-06-23 20:37 UTC by cgrisdale

New Features:
-Support for importing CIViC evidence with direction 'Does not support Sensitivity'
-Support new CIViC naming convention for fusions with known exon boundaries

2021-07-02 17:46 UTC, creisle commented
Because this adds new features, we should probably make it a minor version release so v5.2.0

2021-07-05 19:49 UTC, elewis2 approved these changes

2021-07-05 20:05 UTC, elewis2 commented on package.json
> +  "version": "5.1.1",
should be minor version change

2021-07-05 20:18 UTC, creisle requested changes
Because this adds new features, we should probably make it a minor version release so v5.2.0

2021-07-05 20:26 UTC, creisle approved these changes

2021-07-07 19:01 UTC, elewis2 approved these changes

2021-07-07 19:41 UTC, merged