Feature/write test for ensembl fetchandloadbyid
bcgsc/pori_graphkb_loader pull request #90
Opened 2022-04-13 16:06 UTC by mathieulemieux

Replace PR# [74](https://github.com/bcgsc/pori_graphkb_loader/pull/74).
This is for the fetchAndLoadById function only.
uploadFile is comming next on the same model.

2022-04-14 19:53 UTC, creisle requested changes

2022-04-19 15:19 UTC, mathieulemieux commented on test/ensembl/ensembl.fetchAndLoadById.test.js
> +    const { ApiConnection: mockApiConnection, ...graphkb } = jest.requireActual('../../src/graphkb');
I'm mocking only the request function of the ApiConnection (line #10); Everything on line #9 is 'jest.requireActual'.

2022-04-19 15:45 UTC, mathieulemieux commented on test/ensembl/ensembl.fetchAndLoadById.test.js
> +    fetchMock.get(ensemblUrl, () => ({ Parent: sourceIdGene }));
ok

2022-05-03 18:21 UTC, creisle submitted a review, later dismissed

2022-05-03 18:21 UTC, creisle commented on test/ensembl/ensembl.fetchAndLoadById.test.js
> +        this.mockFile = path.join(__dirname, '../data/ensembl_fetchAndLoadById_requests.json');
as discussed in zoom would just be good to add a 1 liner here mentioning why the order of the items in the file is important etc

2022-05-03 18:44 UTC, creisle approved these changes

2022-05-03 22:59 UTC, merged